<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>preview</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <CodeAnalysisTreatWarningsAsErrors>false</CodeAnalysisTreatWarningsAsErrors>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisMode>Recommended</AnalysisMode>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <Deterministic>true</Deterministic>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <PropertyGroup Condition="$([System.String]::Copy('$(MSBuildProjectName)').Contains('.Tests'))">
    <IsTestProject>true</IsTestProject>
    <NoWarn>$(NoWarn);CS0436;CS0649;CS8602;FLM3002;FLM3004</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'Fletched.Benchmarks'">
    <NoWarn>$(NoWarn);CS0436;CS0649;CS8602;FLM3002;FLM3004</NoWarn>
  </PropertyGroup>
</Project>
