using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Fletched.Roslyn.Pipeline;
using Microsoft.CodeAnalysis;

namespace Fletched.Roslyn.Emitters;
/// Generates Proxy&lt;T&gt; extension members for a [Fact] type,
/// and a partial EngineContext with FactTable properties.
/// </summary>
public sealed class FactEmitter
{
    private readonly INamedTypeSymbol _factType;

    public FactEmitter(INamedTypeSymbol factType) => _factType = factType;

    public string EmitProxy()
    {
        var sb = new StringBuilder();
        string fqName = _factType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string simpleName = _factType.Name;
        string ns = SourceSymbolHelpers.GetNamespace(_factType);
        string proxyTypeName = string.Concat(SourceSymbolHelpers
            .GetContainingTypes(_factType)
            .Select(type => type.Name)) + simpleName + "ProxyExtensions";
        int indentLevel = 0;

        AppendLine(sb, ref indentLevel, "// <auto-generated />");
        AppendLine(sb, ref indentLevel, "#nullable enable");
        AppendLine(sb, ref indentLevel);
        if (!string.IsNullOrEmpty(ns))
        {
            AppendLine(sb, ref indentLevel, $"namespace {ns};");
            AppendLine(sb, ref indentLevel);
        }

        // C# 14 extension members for Proxy<T> — must be inside a static class
        AppendLine(sb, ref indentLevel, $"public static class {proxyTypeName}");
        AppendLine(sb, ref indentLevel, "{");
        indentLevel++;
        AppendLine(sb, ref indentLevel, $"extension(global::Fletched.Core.Proxy<{fqName}> _proxy)");
        AppendLine(sb, ref indentLevel, "{");
        indentLevel++;
        foreach (ISymbol member in _factType.GetMembers())
        {
            if (member is IPropertySymbol prop && !prop.IsStatic && prop.GetMethod is not null)
            {
                string fieldTypeName = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                AppendLine(sb, ref indentLevel, $"public global::Fletched.Core.LogicExpr<{fieldTypeName}> {prop.Name}");
                AppendLine(sb, ref indentLevel, "{");
                indentLevel++;
                AppendLine(sb, ref indentLevel, "get");
                AppendLine(sb, ref indentLevel, "{");
                indentLevel++;
                AppendLine(sb, ref indentLevel, $"var _varNode = new global::Fletched.Core.IR.VarNode(_proxy.VariableName, typeof({fqName}));");
                AppendLine(sb, ref indentLevel, $"var _member = typeof({fqName}).GetProperty(\"{prop.Name}\")!;");
                AppendLine(sb, ref indentLevel, $"return new global::Fletched.Core.LogicExpr<{fieldTypeName}>(new global::Fletched.Core.IR.FieldNode(_varNode, _member, typeof({fieldTypeName})));");
                indentLevel--;
                AppendLine(sb, ref indentLevel, "}");
                indentLevel--;
                AppendLine(sb, ref indentLevel, "}");
            }
        }
        indentLevel--;
        AppendLine(sb, ref indentLevel, "}");
        indentLevel--;
        AppendLine(sb, ref indentLevel, "}");

        return sb.ToString();
    }

    public string EmitEngineContextProperty()
    {
        var sb = new StringBuilder();
        string fqName = _factType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string simpleName = _factType.Name;
        string propName = simpleName.EndsWith("s") ? simpleName : simpleName + "s";
        string ns = SourceSymbolHelpers.GetNamespace(_factType);
        INamedTypeSymbol? moduleRoot = SourceSymbolHelpers.GetModuleRoot(_factType);
        int indentLevel = 0;

        AppendLine(sb, ref indentLevel, "// <auto-generated />");
        AppendLine(sb, ref indentLevel, "#nullable enable");
        AppendLine(sb, ref indentLevel);

        if (moduleRoot is null)
        {
            AppendLine(sb, ref indentLevel, "namespace Fletched.Core.Runtime;");
            AppendLine(sb, ref indentLevel);
            AppendLine(sb, ref indentLevel, "public partial class EngineContext");
            AppendLine(sb, ref indentLevel, "{");
            indentLevel++;
            AppendLine(sb, ref indentLevel, $"public global::Fletched.Core.Runtime.FactTable<{fqName}> {propName} {{ get; set; }}");
            AppendLine(sb, ref indentLevel, $"= new global::Fletched.Core.Runtime.FactTable<{fqName}>();");
            indentLevel--;
            AppendLine(sb, ref indentLevel, "}");
            return sb.ToString();
        }

        if (!string.IsNullOrEmpty(ns))
        {
            AppendLine(sb, ref indentLevel, $"namespace {ns};");
            AppendLine(sb, ref indentLevel);
        }

        foreach (INamedTypeSymbol containingType in SourceSymbolHelpers.GetContainingTypesIncludingSelf(moduleRoot))
        {
            AppendLine(sb, ref indentLevel, SourceSymbolHelpers.GetTypeDeclaration(containingType));
            AppendLine(sb, ref indentLevel, "{");
            indentLevel++;
        }

        AppendLine(sb, ref indentLevel, "public sealed partial class EngineContext");
        AppendLine(sb, ref indentLevel, "{");
        indentLevel++;
        AppendLine(sb, ref indentLevel, $"public global::Fletched.Core.Runtime.FactTable<{fqName}> {propName} {{ get; set; }}");
        AppendLine(sb, ref indentLevel, $"= new global::Fletched.Core.Runtime.FactTable<{fqName}>();");
        indentLevel--;
        AppendLine(sb, ref indentLevel, "}");

        foreach (INamedTypeSymbol _ in SourceSymbolHelpers.GetContainingTypesIncludingSelf(moduleRoot).Reverse())
        {
            indentLevel--;
            AppendLine(sb, ref indentLevel, "}");
        }

        return sb.ToString();
    }

    public string EmitIndexes()
    {
        ImmutableArray<FactIndexDeclaration> indexes = FactIndexModel.GetIndexes(_factType);
        if (!indexes.Any(index => !index.IsImplicit))
            return string.Empty;

        var sb = new StringBuilder();
        int indentLevel = 0;
        AppendLine(sb, ref indentLevel, "// <auto-generated />");
        AppendLine(sb, ref indentLevel, "#nullable enable");
        AppendLine(sb, ref indentLevel);

        string ns = SourceSymbolHelpers.GetNamespace(_factType);
        if (!string.IsNullOrEmpty(ns))
        {
            AppendLine(sb, ref indentLevel, $"namespace {ns};");
            AppendLine(sb, ref indentLevel);
        }

        foreach (INamedTypeSymbol containingType in SourceSymbolHelpers.GetContainingTypes(_factType))
        {
            AppendLine(sb, ref indentLevel, SourceSymbolHelpers.GetTypeDeclaration(containingType));
            AppendLine(sb, ref indentLevel, "{");
            indentLevel++;
        }

        string factTypeName = _factType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        AppendLine(sb, ref indentLevel, $"internal static class {FactIndexModel.GetIndexClassName(_factType)}");
        AppendLine(sb, ref indentLevel, "{");
        indentLevel++;

        foreach (FactIndexDeclaration index in indexes.Where(index => !index.IsImplicit))
        {
            string membersExpression = $"global::System.Collections.Immutable.ImmutableArray.Create<string>({string.Join(", ", index.Members.Select(member => $"\"{member}\""))})";
            string fieldType = index.Kind == FactIndexKindModel.Range
                ? $"global::Fletched.Core.Runtime.GeneratedFactRangeIndexAccessor<{factTypeName}, {RenderType(index.MemberTypes[0])}>"
                : $"global::Fletched.Core.Runtime.GeneratedFactIndexAccessor<{factTypeName}, {RenderKeyType(index)}>";

            AppendLine(sb, ref indentLevel, $"public static readonly {fieldType} {index.FieldName} =");
            AppendLine(sb, ref indentLevel, "    new(");
            indentLevel++;
            AppendLine(sb, ref indentLevel, $"\"{index.Name}\",");
            if (index.Kind == FactIndexKindModel.Range)
            {
                AppendLine(sb, ref indentLevel, $"\"{index.Members[0]}\",");
                AppendLine(sb, ref indentLevel, $"static fact => {RenderKeyAccess("fact", index)});");
            }
            else
            {
                AppendLine(sb, ref indentLevel, $"{membersExpression},");
                AppendLine(sb, ref indentLevel, $"static fact => {RenderKeyAccess("fact", index)});");
            }
            indentLevel--;
            AppendLine(sb, ref indentLevel);
        }

        indentLevel--;
        AppendLine(sb, ref indentLevel, "}");

        foreach (INamedTypeSymbol _ in SourceSymbolHelpers.GetContainingTypes(_factType).Reverse())
        {
            indentLevel--;
            AppendLine(sb, ref indentLevel, "}");
        }

        return sb.ToString();
    }

    private static string RenderType(ITypeSymbol type) =>
        type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private static string RenderKeyType(FactIndexDeclaration index)
    {
        if (index.Members.Length == 1)
            return RenderType(index.MemberTypes[0]);

        return $"({string.Join(", ", index.MemberTypes.Zip(index.Members, (type, member) => $"{RenderType(type)} {member}"))})";
    }

    private static string RenderKeyAccess(string variableName, FactIndexDeclaration index)
    {
        if (index.Members.Length == 1)
            return $"{variableName}.{index.Members[0]}";

        return $"({string.Join(", ", index.Members.Select(member => $"{variableName}.{member}"))})";
    }

    private static void AppendLine(StringBuilder sb, ref int indentLevel, string line = "")
    {
        if (line.Length == 0)
        {
            sb.AppendLine();
            return;
        }

        sb.Append(new string(' ', indentLevel * 4));
        sb.AppendLine(line);
    }
}
