using Microsoft.CodeAnalysis;

namespace Fletched.Roslyn.Emitters;

/// <summary>
/// Generates Proxy&lt;T&gt; extension members for a [Fact] type,
/// and a partial EngineContext with FactTable properties.
/// </summary>
public sealed class FactEmitter
{
    private readonly INamedTypeSymbol _factType;

    public FactEmitter(INamedTypeSymbol factType) => _factType = factType;

    public string EmitProxy(string ns)
    {
        var sb = new System.Text.StringBuilder();
        string fqName = _factType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string simpleName = _factType.Name;

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        // C# 14 extension members for Proxy<T>
        sb.AppendLine($"extension(global::Fletched.Core.Proxy<{fqName}> _proxy)");
        sb.AppendLine("{");
        foreach (ISymbol member in _factType.GetMembers())
        {
            if (member is IPropertySymbol prop && !prop.IsStatic && prop.GetMethod is not null)
            {
                string fieldTypeName = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                sb.AppendLine($"    public global::Fletched.Core.LogicExpr<{fieldTypeName}> {prop.Name}");
                sb.AppendLine("    {");
                sb.AppendLine("        get");
                sb.AppendLine("        {");
                sb.AppendLine($"            var _varNode = new global::Fletched.Core.IR.VarNode(_proxy.VariableName, typeof({fqName}));");
                // Use reflection to get MemberInfo
                sb.AppendLine($"            var _member = typeof({fqName}).GetProperty(\"{prop.Name}\")!;");
                sb.AppendLine($"            return new global::Fletched.Core.LogicExpr<{fieldTypeName}>(new global::Fletched.Core.IR.FieldNode(_varNode, _member, typeof({fieldTypeName})));");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
            }
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    public string EmitEngineContextProperty(string ns)
    {
        var sb = new System.Text.StringBuilder();
        string fqName = _factType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string simpleName = _factType.Name;
        string propName = simpleName.EndsWith("s") ? simpleName : simpleName + "s";

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        sb.AppendLine("partial class EngineContext");
        sb.AppendLine("{");
        sb.AppendLine($"    public global::Fletched.Core.Runtime.FactTable<{fqName}> {propName} {{ get; set; }}");
        sb.AppendLine($"        = new global::Fletched.Core.Runtime.FactTable<{fqName}>();");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
