using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Fletched.Roslyn.Pipeline;
using Microsoft.CodeAnalysis;

namespace Fletched.Roslyn.Emitters;

/// <summary>
/// Generates the async extension file for a predicate: a partial record struct with
/// the ExecuteAsync IAsyncEnumerable method using a switch-loop state machine.
/// </summary>
public sealed class PredicateEmitterAsync
{
    private readonly PredicateModel _model;
    private readonly PlanProgram _plan;
    private readonly bool _generateLegacyNames;
    private readonly string _generatedName;
    private readonly string _resultTypeName;
    private readonly string _contextTypeName;
    private readonly bool _isTabledPredicate;

    // Ordered slot list: (variableName, typeName, slot index)
    private readonly List<(string Name, string TypeName, int Slot)> _slots;
    private readonly List<CallEmitInfo> _calls = [];
    private int _nextCallToEmit;

    // Label → unique integer id for switch dispatch
    private readonly Dictionary<string, int> _labelIds = new();
    private int _labelIdCounter;

    // Reserved PC values for the switch-loop state machine
    private const int PcFail = -1;
    private const int PcResume = -2;
    private const int PcSuccess = -3;

    private sealed record CallEmitInfo(
        int Id,
        string EnumeratorVar,
        string ActiveVar,
        string ProducedVar,
        string ResultTypeName);

    private string GeneratedName => _generatedName;

    private string ResultTypeName => _resultTypeName;

    public PredicateEmitterAsync(PredicateModel model, PlanProgram plan, bool generateLegacyNames)
    {
        _model = model;
        _plan = plan;
        _generateLegacyNames = generateLegacyNames;
        _generatedName = _generateLegacyNames
            ? _model.Name
            : $"{_model.Name}Arity{_model.Arity}";
        _resultTypeName = _generateLegacyNames
            ? $"{_model.Name}Result"
            : $"{_generatedName}Result";
        _contextTypeName = SourceSymbolHelpers.GetContextTypeName(_model.Symbol);
        _isTabledPredicate = PredicateAttributeHelpers.IsTabledPredicate(_model.Symbol);

        var slotTypes = plan.SlotMap.ToDictionary(
            kv => kv.Value,
            kv => kv.Key.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
        var slotNames = plan.SlotMap.ToDictionary(kv => kv.Value, kv => kv.Key.Name);

        foreach (PlanBlock block in new[] { plan.Entry }.Concat(plan.Blocks))
        {
            foreach (PlanInstruction instruction in block.Instructions)
            {
                CollectSlots(instruction, slotNames, slotTypes);
                if (instruction is CallInstr call)
                {
                    int callId = _calls.Count;
                    _calls.Add(new CallEmitInfo(
                        callId,
                        EnumeratorVar: $"_callEnum_{callId}",
                        ActiveVar: $"_callActive_{callId}",
                        ProducedVar: $"_callProduced_{callId}",
                        ResultTypeName: GetCallResultTypeName(call)));
                }
            }
        }

        _slots = slotTypes
            .OrderBy(kv => kv.Key)
            .Select(kv => (ResolveSlotName(slotNames, kv.Key), kv.Value, kv.Key))
            .ToList();

        // Assign integer ids to all labels
        var allBlocks = new[] { plan.Entry }.Concat(plan.Blocks);
        foreach (PlanBlock block in allBlocks)
        {
            _labelIds[block.Label] = _labelIdCounter++;
        }
    }

    public string Emit()
    {
        var ctx = new EmitContext(_model.Name, GeneratedName);

        ctx.AppendLine($"// <auto-generated />");
        ctx.AppendLine($"#nullable enable");
        ctx.AppendLine($"#pragma warning disable CS0164, CS0162, CS8600, CS8618, CS8625");
        ctx.AppendLine();

        SourceSymbolHelpers.OpenDeclarationScope(ctx, _model.Symbol);

        EmitPredicatePartial(ctx);
        SourceSymbolHelpers.CloseDeclarationScope(ctx, _model.Symbol);
        EmitModuleQueryWrapper(ctx);

        return ctx.Code.ToString();
    }

    private void EmitPredicatePartial(EmitContext ctx)
    {
        ctx.AppendLine($"partial record struct {_model.Name}");
        ctx.AppendLine("{");
        using (ctx.Indent())
        {
            if (_generateLegacyNames)
            {
                // Emit the legacy ExecuteAsync convenience wrapper that delegates to the arity-specific method
                ctx.AppendLine($"public async System.Collections.Generic.IAsyncEnumerable<{ResultTypeName}> ExecuteAsync({_contextTypeName} ctx, global::Fletched.Core.Performance.IExecutionObserver? observer = null, global::Fletched.Core.Runtime.QueryExecutionOptions? options = null, [System.Runtime.CompilerServices.EnumeratorCancellation] System.Threading.CancellationToken cancellationToken = default)");
                ctx.AppendLine("{");
                using (ctx.Indent())
                {
                    if (_isTabledPredicate)
                        ctx.AppendLine($"foreach (var item in ExecuteTabledArity{_model.Arity}(ctx, \"{GetDefaultCanonicalCall()}\", observer, options))");
                    else
                        ctx.AppendLine($"await foreach (var item in ExecuteAsyncArity{_model.Arity}(ctx, observer, options, cancellationToken))");
                    ctx.AppendLine("{");
                    using (ctx.Indent())
                    {
                        if (_isTabledPredicate)
                            ctx.AppendLine("cancellationToken.ThrowIfCancellationRequested();");
                        ctx.AppendLine("yield return item;");
                    }
                    ctx.AppendLine("}");
                }
                ctx.AppendLine("}");
                ctx.AppendLine();
            }
            EmitExecuteAsyncMethod(ctx);
        }
        ctx.AppendLine("}");
    }

    private void EmitExecuteAsyncMethod(EmitContext ctx)
    {
        _notCounter = 0;
        _nextCallToEmit = 0;

        ctx.AppendLine($"public async System.Collections.Generic.IAsyncEnumerable<{ResultTypeName}> ExecuteAsyncArity{_model.Arity}({_contextTypeName} ctx, global::Fletched.Core.Performance.IExecutionObserver? observer = null, global::Fletched.Core.Runtime.QueryExecutionOptions? options = null, [System.Runtime.CompilerServices.EnumeratorCancellation] System.Threading.CancellationToken cancellationToken = default)");
        ctx.AppendLine("{");
        using (ctx.Indent())
        {
            ctx.AppendLine($"var state = {ctx.StateTypeName}.Create();");
            ctx.AppendLine($"var cps = new System.Collections.Generic.Stack<global::Fletched.Core.Runtime.ChoicePoint>();");
            ctx.AppendLine("var metrics = options?.Metrics;");

            EmitIndexVarDecls(ctx);
            EmitCallVarDecls(ctx);

            int entryId = _labelIds[_plan.Entry.Label];
            ctx.AppendLine($"int _pc = {entryId};");
            ctx.AppendLine();

            ctx.AppendLine("while (true)");
            ctx.AppendLine("{");
            using (ctx.Indent())
            {
                ctx.AppendLine("switch (_pc)");
                ctx.AppendLine("{");
                using (ctx.Indent())
                {
                    // FAIL
                    ctx.AppendLine($"case {PcFail}:");
                    using (ctx.Indent())
                    {
                        ctx.AppendLine($"_pc = {PcResume};");
                        ctx.AppendLine("break;");
                    }
                    ctx.AppendLine();

                    // RESUME
                    ctx.AppendLine($"case {PcResume}:");
                    using (ctx.Indent())
                    {
                        ctx.AppendLine("if (!cps.TryPop(out var _cp))");
                        ctx.AppendLine("{");
                        using (ctx.Indent())
                            ctx.AppendLine("yield break;");
                        ctx.AppendLine("}");
                        ctx.AppendLine("state.Unwind(_cp.TrailTop);");
                        ctx.AppendMetricIncrement("BacktrackCount");
                        ctx.AppendQueryMetricIncrement("Backtracks");
                        ctx.AppendLine("observer?.OnBacktrack();");
                        ctx.AppendLine("_pc = _cp.LabelId;");
                        ctx.AppendLine("break;");
                    }
                    ctx.AppendLine();

                    // SUCCESS
                    ctx.AppendLine($"case {PcSuccess}:");
                    using (ctx.Indent())
                    {
                        ctx.AppendLine("cancellationToken.ThrowIfCancellationRequested();");
                        string projection = string.Join(", ", _model.Parameters.Select(p => $"state.{p.Name}"));
                        ctx.AppendLine($"yield return new {ResultTypeName}({projection});");
                        ctx.AppendQueryMetricIncrement("ResultsEmitted");
                        ctx.AppendLine($"_pc = {PcResume};");
                        ctx.AppendLine("break;");
                    }
                    ctx.AppendLine();

                    // One case per block
                    var allBlocks = new[] { _plan.Entry }.Concat(_plan.Blocks);
                    foreach (PlanBlock block in allBlocks)
                    {
                        ctx.AppendLine($"case {_labelIds[block.Label]}:");
                        EmitBlock(block, ctx);
                    }

                    // Safety default
                    ctx.AppendLine("default:");
                    using (ctx.Indent())
                        ctx.AppendLine("yield break;");
                }
                ctx.AppendLine("}");
            }
            ctx.AppendLine("}");
        }
        ctx.AppendLine("}");
    }

    private void EmitModuleQueryWrapper(EmitContext ctx)
    {
        INamedTypeSymbol? moduleRoot = SourceSymbolHelpers.GetModuleRoot(_model.Symbol);
        if (moduleRoot is null || _model.Symbol.DeclaredAccessibility != Accessibility.Public)
            return;

        string moduleDeclaration = SourceSymbolHelpers.GetTypeDeclaration(moduleRoot);
        string predicateTypeName = _model.Symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string resultTypeName = SourceSymbolHelpers.GetQualifiedSiblingTypeName(_model.Symbol, ResultTypeName);
        string wrapperName = _generateLegacyNames
            ? $"Query_{_model.Name}Async"
            : $"Query_{GeneratedName}Async";

        ctx.AppendLine();
        ctx.AppendLine(moduleDeclaration);
        ctx.AppendLine("{");
        using (ctx.Indent())
        {
            ctx.AppendLine($"public static async System.Collections.Generic.IAsyncEnumerable<{resultTypeName}> {wrapperName}({_contextTypeName} ctx, global::Fletched.Core.Performance.IExecutionObserver? observer = null, global::Fletched.Core.Runtime.QueryExecutionOptions? options = null, [System.Runtime.CompilerServices.EnumeratorCancellation] System.Threading.CancellationToken cancellationToken = default)");
            ctx.AppendLine("{");
            using (ctx.Indent())
            {
                if (_isTabledPredicate)
                    ctx.AppendLine($"foreach (var item in default({predicateTypeName}).ExecuteTabledArity{_model.Arity}(ctx, \"{GetDefaultCanonicalCall()}\", observer, options))");
                else
                    ctx.AppendLine($"await foreach (var item in default({predicateTypeName}).ExecuteAsyncArity{_model.Arity}(ctx, observer, options, cancellationToken))");
                ctx.AppendLine("{");
                using (ctx.Indent())
                {
                    if (_isTabledPredicate)
                        ctx.AppendLine("cancellationToken.ThrowIfCancellationRequested();");
                    ctx.AppendLine("yield return item;");
                }
                ctx.AppendLine("}");
            }
            ctx.AppendLine("}");
        }
        ctx.AppendLine("}");
    }

    private void EmitIndexVarDecls(EmitContext ctx)
    {
        var indexVars = new HashSet<string>();
        var indexedVars = new HashSet<string>();
        foreach (PlanBlock block in new[] { _plan.Entry }.Concat(_plan.Blocks))
        {
            foreach (PlanInstruction instr in block.Instructions)
            {
                if (instr is IndexInitInstr init)
                {
                    indexVars.Add(init.IndexVar);
                    if (init.IndexedLookup is not null)
                        indexedVars.Add(init.IndexVar);
                }
                if (instr is IndexIncrInstr incr) indexVars.Add(incr.IndexVar);
                if (instr is LoopBindInstr bind) indexVars.Add(bind.IndexVar);
            }
            if (block.Terminator is LoopCheckTerm lc) indexVars.Add(lc.IndexVar);
        }
        foreach (string v in indexVars)
        {
            ctx.AppendLine($"int {v} = 0;");
            if (indexedVars.Contains(v))
                ctx.AppendLine($"int[]? {IndexMatchesVar(v)} = null;");
        }
    }

    private void EmitCallVarDecls(EmitContext ctx)
    {
        foreach (CallEmitInfo call in _calls)
        {
            ctx.AppendLine($"System.Collections.Generic.IEnumerator<{call.ResultTypeName}>? {call.EnumeratorVar} = null;");
            ctx.AppendLine($"bool {call.ActiveVar} = false;");
            ctx.AppendLine($"bool {call.ProducedVar} = false;");
        }
    }

    private void EmitBlock(PlanBlock block, EmitContext ctx)
    {
        // Caller already emitted "case N:"; we emit the braced body.
        ctx.AppendLine("{");
        using (ctx.Indent())
        {
            foreach (PlanInstruction instr in block.Instructions)
                EmitInstruction(instr, block.Label, ctx);
            EmitTerminator(block.Terminator, block.Label, ctx);
        }
        ctx.AppendLine("}");
        ctx.AppendLine();
    }

    private void EmitInstruction(PlanInstruction instr, string blockLabel, EmitContext ctx)
    {
        switch (instr)
        {
            case UnifyInstr u:
                EmitUnify(u, ctx);
                break;

            case ConstraintInstr c:
                EmitConstraint(c, ctx);
                break;

            case AssignInstr a:
                ctx.AppendLine($"state.{SlotName(a.Slot)} = {EmitValue(a.Value)};");
                ctx.AppendLine($"state.{SlotName(a.Slot)}_bound = true;");
                break;

            case IndexInitInstr init:
                EmitIndexInit(init, ctx);
                break;

            case LoopBindInstr bind:
                EmitLoopBind(bind, ctx);
                break;

            case IndexIncrInstr incr:
                ctx.AppendLine($"{incr.IndexVar}++;");
                break;

            case CompInstr comp:
                EmitComp(comp, ctx);
                break;

            case CallInstr call:
                EmitCall(call, blockLabel, ctx);
                break;

            case NotInstr not:
                EmitNot(not, ctx);
                break;
        }
    }

    private void EmitIndexInit(IndexInitInstr init, EmitContext ctx)
    {
        string tableProp = TablePropertyName(init.FactType);
        string matchesVar = IndexMatchesVar(init.IndexVar);

        if (init.IndexedLookup is null)
        {
            ctx.AppendLine($"{init.IndexVar} = 0;");
            ctx.AppendMetricIncrement("FactScans");
            ctx.AppendLine($"observer?.OnFactScan(\"{init.FactType.Name}\");");
            return;
        }

        if (init.IndexedLookup.AccessPathKind == FactAccessPathKind.RangeIndex)
        {
            string accessorExpression = BuildRangeAccessorExpression(init);
            string keyTypeName = GetIndexMemberTypeName(init.FactType, init.IndexedLookup.Members[0]);
            string hasLowerExpression = BuildRangeBoundPresenceExpression(init.IndexedLookup.Range!.Lower);
            string lowerExpression = BuildRangeBoundValueExpression(init.IndexedLookup.Range!.Lower, keyTypeName);
            string hasUpperExpression = BuildRangeBoundPresenceExpression(init.IndexedLookup.Range!.Upper);
            string upperExpression = BuildRangeBoundValueExpression(init.IndexedLookup.Range!.Upper, keyTypeName);

            ctx.AppendLine($"{init.IndexVar} = 0;");
            ctx.AppendLine($"if ({hasLowerExpression} || {hasUpperExpression})");
            ctx.AppendLine("{");
            using (ctx.Indent())
            {
                ctx.AppendQueryMetricIncrement("IndexLookups");
                ctx.AppendQueryMetricIncrement("RangeIndexLookups");
                ctx.AppendLine($"if (ctx.{tableProp}.TryGetRange({accessorExpression}, {hasLowerExpression}, {lowerExpression}, {init.IndexedLookup.Range.LowerInclusive.ToString().ToLowerInvariant()}, {hasUpperExpression}, {upperExpression}, {init.IndexedLookup.Range.UpperInclusive.ToString().ToLowerInvariant()}, out {matchesVar}))");
                ctx.AppendLine("{");
                using (ctx.Indent())
                {
                    ctx.AppendMetricIncrement("IndexHits");
                    ctx.AppendQueryMetricIncrement("IndexHits");
                    ctx.AppendQueryMetricAdd("IndexRowsReturned", $"{matchesVar}.Length");
                    ctx.AppendLine($"observer?.OnIndexHit(\"{init.FactType.Name}\");");
                }
                ctx.AppendLine("}");
                ctx.AppendLine("else");
                ctx.AppendLine("{");
                using (ctx.Indent())
                {
                    ctx.AppendQueryMetricIncrement("IndexMisses");
                    ctx.AppendLine($"_pc = {PcFail};");
                    ctx.AppendLine("break;");
                }
                ctx.AppendLine("}");
            }
            ctx.AppendLine("}");
            ctx.AppendLine("else");
            ctx.AppendLine("{");
            using (ctx.Indent())
            {
                ctx.AppendLine($"{matchesVar} = null;");
                ctx.AppendMetricIncrement("FactScans");
                ctx.AppendLine($"observer?.OnFactScan(\"{init.FactType.Name}\");");
            }
            ctx.AppendLine("}");
            return;
        }

        string accessor = BuildEqualityAccessorExpression(init);
        string keyExpression = BuildEqualityKeyExpression(init.IndexedLookup);
        string boundCondition = BuildEqualityBoundCondition(init.IndexedLookup);
        string lookupCounter = init.IndexedLookup.AccessPathKind == FactAccessPathKind.CompositeEqualityIndex
            ? "CompositeIndexLookups"
            : "EqualityIndexLookups";

        ctx.AppendLine($"{init.IndexVar} = 0;");
        if (!string.IsNullOrEmpty(boundCondition))
        {
            ctx.AppendLine($"if ({boundCondition})");
            ctx.AppendLine("{");
            using (ctx.Indent())
            {
                ctx.AppendQueryMetricIncrement("IndexLookups");
                ctx.AppendQueryMetricIncrement(lookupCounter);
                ctx.AppendLine($"if (ctx.{tableProp}.TryGetIndex({accessor}, {keyExpression}, out {matchesVar}))");
                ctx.AppendLine("{");
                using (ctx.Indent())
                {
                    ctx.AppendMetricIncrement("IndexHits");
                    ctx.AppendQueryMetricIncrement("IndexHits");
                    ctx.AppendQueryMetricAdd("IndexRowsReturned", $"{matchesVar}.Length");
                    ctx.AppendLine($"observer?.OnIndexHit(\"{init.FactType.Name}\");");
                }
                ctx.AppendLine("}");
                ctx.AppendLine("else");
                ctx.AppendLine("{");
                using (ctx.Indent())
                {
                    ctx.AppendQueryMetricIncrement("IndexMisses");
                    ctx.AppendLine($"_pc = {PcFail};");
                    ctx.AppendLine("break;");
                }
                ctx.AppendLine("}");
            }
            ctx.AppendLine("}");
            ctx.AppendLine("else");
            ctx.AppendLine("{");
            using (ctx.Indent())
            {
                ctx.AppendLine($"{matchesVar} = null;");
                ctx.AppendMetricIncrement("FactScans");
                ctx.AppendLine($"observer?.OnFactScan(\"{init.FactType.Name}\");");
            }
            ctx.AppendLine("}");
            return;
        }

        ctx.AppendQueryMetricIncrement("IndexLookups");
        ctx.AppendQueryMetricIncrement(lookupCounter);
        ctx.AppendLine($"if (ctx.{tableProp}.TryGetIndex({accessor}, {keyExpression}, out {matchesVar}))");
        ctx.AppendLine("{");
        using (ctx.Indent())
        {
            ctx.AppendMetricIncrement("IndexHits");
            ctx.AppendQueryMetricIncrement("IndexHits");
            ctx.AppendQueryMetricAdd("IndexRowsReturned", $"{matchesVar}.Length");
            ctx.AppendLine($"observer?.OnIndexHit(\"{init.FactType.Name}\");");
        }
        ctx.AppendLine("}");
        ctx.AppendLine("else");
        ctx.AppendLine("{");
        using (ctx.Indent())
        {
            ctx.AppendQueryMetricIncrement("IndexMisses");
            ctx.AppendLine($"_pc = {PcFail};");
            ctx.AppendLine("break;");
        }
        ctx.AppendLine("}");
    }

    private void EmitLoopBind(LoopBindInstr bind, EmitContext ctx)
    {
        string tableProp = TablePropertyName(bind.FactType);
        string slotName = SlotName(bind.Slot);

        if (bind.IndexedLookup is null)
        {
            ctx.AppendQueryMetricIncrement("FactRowsScanned");
            ctx.AppendLine($"state.{slotName} = ctx.{tableProp}.Data[{bind.IndexVar}];");
            ctx.AppendLine($"state.{slotName}_bound = true;");
            return;
        }

        string matchesVar = IndexMatchesVar(bind.IndexVar);
        if (bind.IndexedLookup.AccessPathKind == FactAccessPathKind.RangeIndex)
        {
            string hasIndexCondition = BuildRangeHasIndexCondition(bind.IndexedLookup);
            ctx.AppendLine($"if ({hasIndexCondition})");
            ctx.AppendLine("{");
            using (ctx.Indent())
            {
                ctx.AppendLine($"state.{slotName} = ctx.{tableProp}.Data[{matchesVar}![{bind.IndexVar}]];");
                ctx.AppendLine($"state.{slotName}_bound = true;");
            }
            ctx.AppendLine("}");
            ctx.AppendLine("else");
            ctx.AppendLine("{");
            using (ctx.Indent())
            {
                ctx.AppendQueryMetricIncrement("FactRowsScanned");
                ctx.AppendLine($"state.{slotName} = ctx.{tableProp}.Data[{bind.IndexVar}];");
                ctx.AppendLine($"state.{slotName}_bound = true;");
            }
            ctx.AppendLine("}");
            return;
        }

        string boundCondition = BuildEqualityBoundCondition(bind.IndexedLookup);
        if (!string.IsNullOrEmpty(boundCondition))
        {
            ctx.AppendLine($"if ({boundCondition})");
            ctx.AppendLine("{");
            using (ctx.Indent())
            {
                ctx.AppendLine($"state.{slotName} = ctx.{tableProp}.Data[{matchesVar}![{bind.IndexVar}]];");
                ctx.AppendLine($"state.{slotName}_bound = true;");
            }
            ctx.AppendLine("}");
            ctx.AppendLine("else");
            ctx.AppendLine("{");
            using (ctx.Indent())
            {
                ctx.AppendQueryMetricIncrement("FactRowsScanned");
                ctx.AppendLine($"state.{slotName} = ctx.{tableProp}.Data[{bind.IndexVar}];");
                ctx.AppendLine($"state.{slotName}_bound = true;");
            }
            ctx.AppendLine("}");
            return;
        }

        ctx.AppendLine($"state.{slotName} = ctx.{tableProp}.Data[{matchesVar}![{bind.IndexVar}]];");
        ctx.AppendLine($"state.{slotName}_bound = true;");
    }

    private void EmitLoopCheck(LoopCheckTerm loopCheck, EmitContext ctx)
    {
        string tableProp = TablePropertyName(loopCheck.FactType);

        if (loopCheck.IndexedLookup is null)
        {
            ctx.AppendLine($"if ({loopCheck.IndexVar} >= ctx.{tableProp}.Data.Length) {{ _pc = {PcFail}; break; }}");
            ctx.AppendLine($"_pc = {_labelIds[loopCheck.BodyLabel]};");
            ctx.AppendLine("break;");
            return;
        }

        string matchesVar = IndexMatchesVar(loopCheck.IndexVar);
        string hasIndexCondition = loopCheck.IndexedLookup.AccessPathKind == FactAccessPathKind.RangeIndex
            ? BuildRangeHasIndexCondition(loopCheck.IndexedLookup)
            : BuildEqualityBoundCondition(loopCheck.IndexedLookup);

        if (!string.IsNullOrEmpty(hasIndexCondition))
        {
            ctx.AppendLine($"if ({hasIndexCondition})");
            ctx.AppendLine("{");
            using (ctx.Indent())
                ctx.AppendLine($"if ({matchesVar} is null || {loopCheck.IndexVar} >= {matchesVar}.Length) {{ _pc = {PcFail}; break; }}");
            ctx.AppendLine("}");
            ctx.AppendLine("else");
            ctx.AppendLine("{");
            using (ctx.Indent())
                ctx.AppendLine($"if ({loopCheck.IndexVar} >= ctx.{tableProp}.Data.Length) {{ _pc = {PcFail}; break; }}");
            ctx.AppendLine("}");
            ctx.AppendLine($"_pc = {_labelIds[loopCheck.BodyLabel]};");
            ctx.AppendLine("break;");
            return;
        }

        ctx.AppendLine($"if ({matchesVar} is null || {loopCheck.IndexVar} >= {matchesVar}.Length) {{ _pc = {PcFail}; break; }}");
        ctx.AppendLine($"_pc = {_labelIds[loopCheck.BodyLabel]};");
        ctx.AppendLine("break;");
    }

    private string BuildEqualityAccessorExpression(IndexInitInstr init)
    {
        string factTypeName = init.FactType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        if (!init.IndexedLookup!.IsImplicit)
            return $"{FactIndexModel.GetIndexClassQualifiedName((INamedTypeSymbol)init.FactType)}.{init.IndexedLookup.AccessorFieldName}";

        string keyType = init.IndexedLookup.Members.Length == 1
            ? GetIndexMemberTypeName(init.FactType, init.IndexedLookup.Members[0])
            : $"({string.Join(", ", init.IndexedLookup.Members.Select(member => GetIndexMemberTypeName(init.FactType, member)))})";
        string membersExpression = $"global::System.Collections.Immutable.ImmutableArray.Create<string>({string.Join(", ", init.IndexedLookup.Members.Select(member => $"\"{member}\""))})";
        string getterExpression = init.IndexedLookup.Members.Length == 1
            ? $"fact.{init.IndexedLookup.Members[0]}"
            : $"({string.Join(", ", init.IndexedLookup.Members.Select(member => $"fact.{member}"))})";
        return $"new global::Fletched.Core.Runtime.GeneratedFactIndexAccessor<{factTypeName}, {keyType}>(\"{init.IndexedLookup.IndexName}\", {membersExpression}, static fact => {getterExpression})";
    }

    private string BuildRangeAccessorExpression(IndexInitInstr init)
    {
        string factTypeName = init.FactType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        if (!init.IndexedLookup!.IsImplicit)
            return $"{FactIndexModel.GetIndexClassQualifiedName((INamedTypeSymbol)init.FactType)}.{init.IndexedLookup.AccessorFieldName}";

        string memberName = init.IndexedLookup.Members[0];
        string keyType = GetIndexMemberTypeName(init.FactType, memberName);
        return $"new global::Fletched.Core.Runtime.GeneratedFactRangeIndexAccessor<{factTypeName}, {keyType}>(\"{init.IndexedLookup.IndexName}\", \"{memberName}\", static fact => fact.{memberName})";
    }

    private string BuildEqualityKeyExpression(IndexedLookupSpec lookup) =>
        lookup.EqualityParts.Length switch
        {
            1 => EmitValue(lookup.EqualityParts[0].Key),
            _ => $"({string.Join(", ", lookup.EqualityParts.Select(part => EmitValue(part.Key)))})"
        };

    private string BuildEqualityBoundCondition(IndexedLookupSpec lookup)
    {
        string[] slotConditions = lookup.EqualityParts
            .Select(part => part.Key)
            .OfType<SlotValue>()
            .Select(slot => $"state.{SlotName(slot.Slot)}_bound")
            .ToArray();
        return string.Join(" && ", slotConditions);
    }

    private string BuildRangeHasIndexCondition(IndexedLookupSpec lookup)
    {
        string lower = BuildRangeBoundPresenceExpression(lookup.Range!.Lower);
        string upper = BuildRangeBoundPresenceExpression(lookup.Range!.Upper);
        return $"{lower} || {upper}";
    }

    private string BuildRangeBoundPresenceExpression(PlanValue? value) =>
        value switch
        {
            null => "false",
            SlotValue slot => $"state.{SlotName(slot.Slot)}_bound",
            _ => "true"
        };

    private string BuildRangeBoundValueExpression(PlanValue? value, string keyTypeName) =>
        value is null
            ? $"default({keyTypeName})"
            : EmitValue(value);

    private string GetIndexMemberTypeName(ITypeSymbol factType, string memberName)
    {
        ISymbol member = factType.GetMembers().First(symbol => symbol.Name == memberName);
        return member switch
        {
            IPropertySymbol property => property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            IFieldSymbol field => field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            _ => "global::System.Object"
        };
    }

    private void EmitCall(CallInstr call, string blockLabel, EmitContext ctx)
    {
        CallEmitInfo callInfo = _calls[_nextCallToEmit++];
        string predTypeName = call.PredicateType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string resultVar = $"_callResult_{callInfo.Id}";

        ctx.AppendLine($"if (!{callInfo.ActiveVar})");
        ctx.AppendLine("{");
        using (ctx.Indent())
        {
            ctx.AppendMetricIncrement("PredicateInvocations");
            ctx.AppendQueryMetricIncrement("PredicateCalls");
            ctx.AppendLine($"observer?.OnPredicateInvocation(\"{call.PredicateType.Name}\");");
            ctx.AppendLine($"global::Fletched.Core.Runtime.RecursionGuard.EnterPredicateInvocation(ctx, \"{call.PredicateType.Name}\", observer);");
            string recursionDepthVar = $"_recursionDepth_{callInfo.Id}";
            ctx.AppendLine($"int {recursionDepthVar} = global::Fletched.Core.Runtime.RecursionGuard.GetCurrentDepth(ctx);");
            ctx.AppendLine($"if ({recursionDepthVar} > 1)");
            ctx.AppendLine("{");
            using (ctx.Indent())
            {
                ctx.AppendMetricIncrement("RecursiveInvocations");
                ctx.AppendDirective("#if METRICS");
                ctx.AppendLine($"global::Fletched.Core.Performance.EngineMetrics.RecursiveDepth.Record({recursionDepthVar});");
                ctx.AppendDirective("#endif");
            }
            ctx.AppendLine("}");
            ctx.AppendLine("try");
            ctx.AppendLine("{");
            using (ctx.Indent())
            {
                if (call.IsTabledCall)
                    ctx.AppendLine($"{callInfo.EnumeratorVar} = default({predTypeName}).ExecuteTabledArity{call.Arity}(ctx, {EmitCanonicalCallExpression(call)}, observer, options).GetEnumerator();");
                else
                    ctx.AppendLine($"{callInfo.EnumeratorVar} = default({predTypeName}).ExecuteArity{call.Arity}(ctx, observer, options).GetEnumerator();");
            }
            ctx.AppendLine("}");
            ctx.AppendLine("catch");
            ctx.AppendLine("{");
            using (ctx.Indent())
            {
                ctx.AppendLine("global::Fletched.Core.Runtime.RecursionGuard.ExitPredicateInvocation(ctx);");
                ctx.AppendLine("throw;");
            }
            ctx.AppendLine("}");
            ctx.AppendLine($"{callInfo.ActiveVar} = true;");
            ctx.AppendLine($"{callInfo.ProducedVar} = false;");
        }
        ctx.AppendLine("}");
        ctx.AppendLine("else");
        ctx.AppendLine("{");
        using (ctx.Indent())
            ctx.AppendMetricIncrement("PredicateInvocationResumes");
        ctx.AppendLine("}");

        string movedNextVar = $"_callMovedNext_{callInfo.Id}";
        ctx.AppendLine($"bool {movedNextVar};");
        ctx.AppendLine("try");
        ctx.AppendLine("{");
        using (ctx.Indent())
            ctx.AppendLine($"{movedNextVar} = {callInfo.EnumeratorVar} is not null && {callInfo.EnumeratorVar}.MoveNext();");
        ctx.AppendLine("}");
        ctx.AppendLine("catch");
        ctx.AppendLine("{");
        using (ctx.Indent())
        {
            ctx.AppendLine($"{callInfo.EnumeratorVar}?.Dispose();");
            ctx.AppendLine($"{callInfo.EnumeratorVar} = null;");
            ctx.AppendLine($"{callInfo.ActiveVar} = false;");
            ctx.AppendLine($"{callInfo.ProducedVar} = false;");
            ctx.AppendLine("global::Fletched.Core.Runtime.RecursionGuard.ExitPredicateInvocation(ctx);");
            ctx.AppendLine("throw;");
        }
        ctx.AppendLine("}");

        ctx.AppendLine($"if (!{movedNextVar})");
        ctx.AppendLine("{");
        using (ctx.Indent())
        {
            ctx.AppendMetricIncrement("PredicateInvocationExhaustions");
            ctx.AppendLine($"if (!{callInfo.ProducedVar})");
            ctx.AppendLine("{");
            using (ctx.Indent())
                ctx.AppendMetricIncrement("PredicateInvocationFailures");
            ctx.AppendLine("}");
            ctx.AppendLine($"{callInfo.EnumeratorVar}?.Dispose();");
            ctx.AppendLine($"{callInfo.EnumeratorVar} = null;");
            ctx.AppendLine($"{callInfo.ActiveVar} = false;");
            ctx.AppendLine($"{callInfo.ProducedVar} = false;");
            ctx.AppendLine("global::Fletched.Core.Runtime.RecursionGuard.ExitPredicateInvocation(ctx);");
            ctx.AppendLine($"_pc = {PcFail};");
            ctx.AppendLine("break;");
        }
        ctx.AppendLine("}");

        ctx.AppendLine($"var {resultVar} = {callInfo.EnumeratorVar}.Current;");
        ctx.AppendLine($"{callInfo.ProducedVar} = true;");
        ctx.AppendQueryMetricIncrement("PredicateCallResults");
        ctx.AppendLine("cps.Push(new global::Fletched.Core.Runtime.ChoicePoint");
        ctx.AppendLine("{");
        using (ctx.Indent())
        {
            ctx.AppendLine($"LabelId = {_labelIds[blockLabel]},");
            ctx.AppendLine("TrailTop = state.Trail.Top");
        }
        ctx.AppendLine("});");
        ctx.AppendMetricIncrement("ChoicePointCount");
        ctx.AppendLine("observer?.OnChoicePoint();");

        for (int i = 0; i < call.ArgumentSlots.Count; i++)
        {
            int slot = call.ArgumentSlots[i];
            string slotName = SlotName(slot);
            string resultField = GetCallResultFieldName(call, i);
            EmitSlotConstUnify(slotName, $"{resultVar}.{resultField}", ctx);
        }
    }

    private int _notCounter;

    private void EmitNot(NotInstr not, EmitContext ctx)
    {
        if (not.SubGoalInstructions.Count == 0) return;

        // Single predicate call: check if any result matches the bound argument values.
        if (not.SubGoalInstructions.Count == 1 && not.SubGoalInstructions[0] is CallInstr call)
        {
            string predTypeName = call.PredicateType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string notFoundVar = $"_notFound_{_notCounter++}";
            string resultVar = $"_notResult_{call.PredicateType.Name}";
            ctx.AppendLine($"bool {notFoundVar} = false;");
            ctx.AppendLine("global::Fletched.Core.Runtime.RecursionGuard.EnterNegationScope(ctx);");
            ctx.AppendLine("try");
            ctx.AppendLine("{");
            using (ctx.Indent())
            {
                if (call.IsTabledCall)
                    ctx.AppendLine($"foreach (var {resultVar} in default({predTypeName}).ExecuteTabledArity{call.Arity}(ctx, {EmitCanonicalCallExpression(call)}, null, options))");
                else
                    ctx.AppendLine($"foreach (var {resultVar} in default({predTypeName}).ExecuteArity{call.Arity}(ctx, null, options))");
                ctx.AppendLine("{");
                using (ctx.Indent())
                {
                    var conditions = new List<string>();
                    for (int i = 0; i < call.ArgumentSlots.Count; i++)
                    {
                        string slotName = SlotName(call.ArgumentSlots[i]);
                        string resultField = GetCallResultFieldName(call, i);
                        conditions.Add($"object.Equals(state.{slotName}, {resultVar}.{resultField})");
                    }
                    string guard = conditions.Count > 0
                        ? string.Join(" && ", conditions)
                        : "true";
                    ctx.AppendLine($"if ({guard}) {{ {notFoundVar} = true; break; }}");
                }
                ctx.AppendLine("}");
            }
            ctx.AppendLine("}");
            ctx.AppendLine("catch");
            ctx.AppendLine("{");
            using (ctx.Indent())
            {
                ctx.AppendLine("global::Fletched.Core.Runtime.RecursionGuard.ExitNegationScope(ctx);");
                ctx.AppendLine("throw;");
            }
            ctx.AppendLine("}");
            ctx.AppendLine("global::Fletched.Core.Runtime.RecursionGuard.ExitNegationScope(ctx);");
            ctx.AppendLine($"if ({notFoundVar}) {{ _pc = {PcFail}; break; }}");
            return;
        }

        // For inline instructions (unify/constraint/comp), build a compound boolean condition.
        // If ALL conditions hold, the subgoal succeeded → Not fails.
        var inlineConditions = new List<string>();
        foreach (PlanInstruction instr in not.SubGoalInstructions)
        {
            switch (instr)
            {
                case UnifyInstr u:
                    inlineConditions.Add($"object.Equals({EmitValue(u.Left)}, {EmitValue(u.Right)})");
                    break;

                case CompInstr c:
                    string op = c.Op switch
                    {
                        CompOp.NotEqual => "!=",
                        CompOp.LessThan => "<",
                        CompOp.GreaterThan => ">",
                        CompOp.LessThanOrEqual => "<=",
                        CompOp.GreaterThanOrEqual => ">=",
                        _ => "!="
                    };
                    inlineConditions.Add($"({EmitValue(c.Left)} {op} {EmitValue(c.Right)})");
                    break;

                case ConstraintInstr c2:
                    if (c2.Method.IsStatic)
                    {
                        string typeName = c2.Method.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        string callArgs = string.Join(", ", c2.Arguments.Select(EmitValue));
                        inlineConditions.Add($"{typeName}.{c2.Method.Name}({callArgs})");
                    }
                    else if (c2.Arguments.Count > 0)
                    {
                        string receiver = EmitValue(c2.Arguments[0]);
                        string callArgs = string.Join(", ", c2.Arguments.Skip(1).Select(EmitValue));
                        string argStr = callArgs.Length > 0 ? callArgs : "";
                        inlineConditions.Add($"{receiver}.{c2.Method.Name}({argStr})");
                    }
                    break;
            }
        }

        if (inlineConditions.Count == 1)
            ctx.AppendLine($"if ({inlineConditions[0]}) {{ _pc = {PcFail}; break; }}");
        else if (inlineConditions.Count > 1)
            ctx.AppendLine($"if ({string.Join(" && ", inlineConditions)}) {{ _pc = {PcFail}; break; }}");
    }

    private void EmitUnify(UnifyInstr u, EmitContext ctx)
    {
        bool leftIsSlot = u.Left is SlotValue;
        bool rightIsSlot = u.Right is SlotValue;
        bool leftIsConst = u.Left is ConstValue;
        bool rightIsConst = u.Right is ConstValue;
        bool leftIsListLiteral = u.Left is ListConsValue or ListEmptyValue;
        bool rightIsListLiteral = u.Right is ListConsValue or ListEmptyValue;

        if (leftIsSlot && rightIsConst)
        {
            string slotName = SlotName(((SlotValue)u.Left).Slot);
            string constVal = EmitValue(u.Right);
            EmitSlotConstUnify(slotName, constVal, ctx);
        }
        else if (leftIsConst && rightIsSlot)
        {
            string slotName = SlotName(((SlotValue)u.Right).Slot);
            string constVal = EmitValue(u.Left);
            EmitSlotConstUnify(slotName, constVal, ctx);
        }
        else if (leftIsSlot && rightIsSlot)
        {
            string a = SlotName(((SlotValue)u.Left).Slot);
            string b = SlotName(((SlotValue)u.Right).Slot);
            EmitSlotSlotUnify(a, b, ctx);
        }
        else if (u.Left is FieldValue && rightIsSlot)
        {
            string slotName = SlotName(((SlotValue)u.Right).Slot);
            string fieldVal = EmitValue(u.Left);
            ctx.AppendLine($"{{ var _fv = {fieldVal};");
            using (ctx.Indent())
                EmitSlotConstUnify(slotName, "_fv", ctx);
            ctx.AppendLine("}");
        }
        else if (leftIsSlot && u.Right is FieldValue)
        {
            string slotName = SlotName(((SlotValue)u.Left).Slot);
            string fieldVal = EmitValue(u.Right);
            ctx.AppendLine($"{{ var _fv = {fieldVal};");
            using (ctx.Indent())
                EmitSlotConstUnify(slotName, "_fv", ctx);
            ctx.AppendLine("}");
        }
        else if (u.Left is FieldValue && u.Right is FieldValue)
        {
            ctx.AppendLine($"if ({EmitValue(u.Left)} != {EmitValue(u.Right)}) {{ _pc = {PcFail}; break; }}");
        }
        else if (leftIsSlot && rightIsListLiteral)
        {
            string slotName = SlotName(((SlotValue)u.Left).Slot);
            EmitSlotConstUnify(slotName, EmitValue(u.Right), ctx);
        }
        else if (leftIsListLiteral && rightIsSlot)
        {
            string slotName = SlotName(((SlotValue)u.Right).Slot);
            EmitSlotConstUnify(slotName, EmitValue(u.Left), ctx);
        }
        else if ((u.Left is FieldValue && rightIsListLiteral) ||
                 (leftIsListLiteral && u.Right is FieldValue))
        {
            ctx.AppendLine($"if (!object.Equals({EmitValue(u.Left)}, {EmitValue(u.Right)})) {{ _pc = {PcFail}; break; }}");
        }
        else if (u.Left is ArithValue || u.Right is ArithValue)
        {
            ctx.AppendLine($"if ({EmitValue(u.Left)} != {EmitValue(u.Right)}) {{ _pc = {PcFail}; break; }}");
        }
        else
        {
            ctx.AppendLine($"if (!object.Equals({EmitValue(u.Left)}, {EmitValue(u.Right)})) {{ _pc = {PcFail}; break; }}");
        }
    }

    private void EmitSlotConstUnify(string slotName, string value, EmitContext ctx)
    {
        int slot = _slots.First(s => s.Name == slotName).Slot;
        ctx.AppendMetricIncrement("UnifyAttempts");
        ctx.AppendQueryMetricIncrement("UnificationAttempts");
        ctx.AppendLine($"observer?.OnUnify({slot});");
        ctx.AppendLine($"if (!state.{slotName}_bound)");
        ctx.AppendLine("{");
        using (ctx.Indent())
        {
            ctx.AppendLine($"state.Trail.Push({slot}, false);");
            ctx.AppendLine($"state.{slotName} = {value};");
            ctx.AppendLine($"state.{slotName}_bound = true;");
        }
        ctx.AppendLine("}");
        ctx.AppendLine($"else if (!object.Equals(state.{slotName}, {value}))");
        ctx.AppendLine("{");
        using (ctx.Indent())
        {
            ctx.AppendMetricIncrement("UnifyFailures");
            ctx.AppendQueryMetricIncrement("UnificationFailures");
            ctx.AppendLine($"observer?.OnUnifyFailure({slot});");
            ctx.AppendLine($"_pc = {PcFail};");
            ctx.AppendLine("break;");
        }
        ctx.AppendLine("}");
        ctx.AppendQueryMetricIncrement("UnificationSuccesses");
    }

    private void EmitSlotSlotUnify(string a, string b, EmitContext ctx)
    {
        int slotA = _slots.First(s => s.Name == a).Slot;
        int slotB = _slots.First(s => s.Name == b).Slot;
        ctx.AppendMetricIncrement("UnifyAttempts");
        ctx.AppendQueryMetricIncrement("UnificationAttempts");
        ctx.AppendLine($"observer?.OnUnify({slotA});");
        ctx.AppendLine($"if (!state.{a}_bound && !state.{b}_bound) {{ /* both unbound - no-op */ }}");
        ctx.AppendLine($"else if (!state.{a}_bound)");
        ctx.AppendLine("{");
        using (ctx.Indent())
        {
            ctx.AppendLine($"state.Trail.Push({slotA}, false);");
            ctx.AppendLine($"state.{a} = state.{b};");
            ctx.AppendLine($"state.{a}_bound = true;");
        }
        ctx.AppendLine("}");
        ctx.AppendLine($"else if (!state.{b}_bound)");
        ctx.AppendLine("{");
        using (ctx.Indent())
        {
            ctx.AppendLine($"state.Trail.Push({slotB}, false);");
            ctx.AppendLine($"state.{b} = state.{a};");
            ctx.AppendLine($"state.{b}_bound = true;");
        }
        ctx.AppendLine("}");
        ctx.AppendLine($"else if (!object.Equals(state.{a}, state.{b}))");
        ctx.AppendLine("{");
        using (ctx.Indent())
        {
            ctx.AppendMetricIncrement("UnifyFailures");
            ctx.AppendQueryMetricIncrement("UnificationFailures");
            ctx.AppendLine($"observer?.OnUnifyFailure({slotA});");
            ctx.AppendLine($"_pc = {PcFail};");
            ctx.AppendLine("break;");
        }
        ctx.AppendLine("}");
        ctx.AppendQueryMetricIncrement("UnificationSuccesses");
    }

    private void EmitConstraint(ConstraintInstr c, EmitContext ctx)
    {
        if (c.Method.IsStatic)
        {
            string typeName = c.Method.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string callArgs = string.Join(", ", c.Arguments.Select(EmitValue));
            ctx.AppendQueryMetricIncrement("ConstraintEvaluations");
            ctx.AppendLine($"if (!{typeName}.{c.Method.Name}({callArgs}))");
            ctx.AppendLine("{");
            using (ctx.Indent())
            {
                ctx.AppendQueryMetricIncrement("ConstraintFailures");
                ctx.AppendLine($"_pc = {PcFail};");
                ctx.AppendLine("break;");
            }
            ctx.AppendLine("}");
        }
        else
        {
            if (c.Arguments.Count > 0)
            {
                string receiver = EmitValue(c.Arguments[0]);
                string callArgs = string.Join(", ", c.Arguments.Skip(1).Select(EmitValue));
                string argStr = callArgs.Length > 0 ? callArgs : "";
                ctx.AppendQueryMetricIncrement("ConstraintEvaluations");
                ctx.AppendLine($"if (!{receiver}.{c.Method.Name}({argStr}))");
                ctx.AppendLine("{");
                using (ctx.Indent())
                {
                    ctx.AppendQueryMetricIncrement("ConstraintFailures");
                    ctx.AppendLine($"_pc = {PcFail};");
                    ctx.AppendLine("break;");
                }
                ctx.AppendLine("}");
            }
        }
    }

    private void EmitComp(CompInstr comp, EmitContext ctx)
    {
        string left = EmitValue(comp.Left);
        string right = EmitValue(comp.Right);
        string op = comp.Op switch
        {
            CompOp.NotEqual => "!=",
            CompOp.LessThan => "<",
            CompOp.GreaterThan => ">",
            CompOp.LessThanOrEqual => "<=",
            CompOp.GreaterThanOrEqual => ">=",
            _ => "!="
        };
        ctx.AppendQueryMetricIncrement("ConstraintEvaluations");
        ctx.AppendLine($"if (!({left} {op} {right}))");
        ctx.AppendLine("{");
        using (ctx.Indent())
        {
            ctx.AppendQueryMetricIncrement("ConstraintFailures");
            ctx.AppendLine($"_pc = {PcFail};");
            ctx.AppendLine("break;");
        }
        ctx.AppendLine("}");
    }

    private void EmitTerminator(PlanTerminator term, string blockLabel, EmitContext ctx)
    {
        switch (term)
        {
            case GotoTerm g:
                ctx.AppendLine($"_pc = {_labelIds[g.TargetLabel]};");
                ctx.AppendLine("break;");
                break;

            case ChoiceTerm choice:
                {
                    int altId = _labelIds.TryGetValue(choice.AlternativeLabel, out int id) ? id : -1;
                    ctx.AppendMetricIncrement("ChoicePointCount");
                    ctx.AppendLine("observer?.OnChoicePoint();");
                    ctx.AppendLine($"cps.Push(new global::Fletched.Core.Runtime.ChoicePoint {{ LabelId = {altId}, TrailTop = state.Trail.Top }});");
                    ctx.AppendLine($"_pc = {_labelIds[choice.NextLabel]};");
                    ctx.AppendLine("break;");
                    break;
                }

            case SucceedTerm:
                ctx.AppendLine($"_pc = {PcSuccess};");
                ctx.AppendLine("break;");
                break;

            case FailTerm:
                ctx.AppendLine($"_pc = {PcFail};");
                ctx.AppendLine("break;");
                break;

            case LoopCheckTerm lc:
                EmitLoopCheck(lc, ctx);
                break;
        }
    }

    private string EmitValue(PlanValue value)
    {
        return value switch
        {
            SlotValue sv => $"state.{SlotName(sv.Slot)}",
            ConstValue cv => EmitConstant(cv.Value, cv.TypeName),
            FieldValue fv => $"{EmitValue(fv.Target)}.{fv.MemberName}",
            ArithValue av => av.Op switch
            {
                ArithOp.Add => $"({EmitValue(av.Left)} + {EmitValue(av.Right)})",
                ArithOp.Subtract => $"({EmitValue(av.Left)} - {EmitValue(av.Right)})",
                ArithOp.Multiply => $"({EmitValue(av.Left)} * {EmitValue(av.Right)})",
                ArithOp.Divide => $"({EmitValue(av.Left)} / {EmitValue(av.Right)})",
                ArithOp.Modulo => $"({EmitValue(av.Left)} % {EmitValue(av.Right)})",
                _ => $"({EmitValue(av.Left)} + {EmitValue(av.Right)})"
            },
            ListEmptyValue lev =>
                $"new global::Fletched.Core.LogicListEmpty<{lev.ElementTypeName}>()",
            ListConsValue lcv =>
                $"new global::Fletched.Core.LogicListCons<{lcv.ElementTypeName}>({EmitValue(lcv.Head)}, {EmitValue(lcv.Tail)})",
            _ => "default"
        };
    }

    private static string EmitConstant(object? value, string typeName)
    {
        if (value is null) return "null";
        if (value is string s) return $"\"{s.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"";
        if (value is bool b) return b ? "true" : "false";
        return $"({typeName}){value}";
    }

    private string SlotName(int slot)
    {
        var entry = _slots.FirstOrDefault(s => s.Slot == slot);
        return entry.Name ?? $"_slot{slot}";
    }

    private string EmitCanonicalCallExpression(CallInstr call)
    {
        if (call.ArgumentSlots.Count == 0)
            return "\"\"";

        var parts = new List<string>(call.ArgumentSlots.Count * 2 - 1);
        for (int i = 0; i < call.ArgumentSlots.Count; i++)
        {
            string slotName = SlotName(call.ArgumentSlots[i]);
            parts.Add($"(state.{slotName}_bound ? \"b:\" + global::Fletched.Core.Runtime.TableKeyFormatter.Format(state.{slotName}) : \"f\")");
            if (i < call.ArgumentSlots.Count - 1)
                parts.Add("\"|\"");
        }

        return $"global::System.String.Concat({string.Join(", ", parts)})";
    }

    private string GetDefaultCanonicalCall()
    {
        return _model.Arity == 0
            ? string.Empty
            : string.Join("|", Enumerable.Repeat("f", _model.Arity));
    }

    private static string IndexMatchesVar(string indexVar) => $"{indexVar}_matches";

    private static void CollectSlots(
        PlanInstruction instruction,
        IDictionary<int, string> slotNames,
        IDictionary<int, string> slotTypes)
    {
        switch (instruction)
        {
            case UnifyInstr unify:
                CollectSlots(unify.Left, slotNames, slotTypes);
                CollectSlots(unify.Right, slotNames, slotTypes);
                break;

            case ConstraintInstr constraint:
                foreach (PlanValue argument in constraint.Arguments)
                    CollectSlots(argument, slotNames, slotTypes);
                break;

            case AssignInstr assign:
                AddIfMissing(slotNames, assign.Slot, $"_slot{assign.Slot}");
                AddIfMissing(slotTypes, assign.Slot, InferTypeName(assign.Value));
                CollectSlots(assign.Value, slotNames, slotTypes);
                break;

            case CompInstr comp:
                CollectSlots(comp.Left, slotNames, slotTypes);
                CollectSlots(comp.Right, slotNames, slotTypes);
                break;

            case LoopBindInstr bind:
                AddIfMissing(slotNames, bind.Slot, $"_slot{bind.Slot}");
                AddIfMissing(slotTypes, bind.Slot, bind.FactType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                if (bind.IndexedLookup is not null)
                    CollectLookupSlots(bind.IndexedLookup, slotNames, slotTypes);
                break;

            case IndexInitInstr init when init.IndexedLookup is not null:
                CollectLookupSlots(init.IndexedLookup, slotNames, slotTypes);
                break;

            case CallInstr call:
                foreach (int slot in call.ArgumentSlots)
                    AddIfMissing(slotNames, slot, $"_slot{slot}");
                break;

            case NotInstr not:
                foreach (PlanInstruction subGoalInstruction in not.SubGoalInstructions)
                    CollectSlots(subGoalInstruction, slotNames, slotTypes);
                break;
        }
    }

    private static void CollectSlots(
        PlanValue value,
        IDictionary<int, string> slotNames,
        IDictionary<int, string> slotTypes)
    {
        switch (value)
        {
            case SlotValue slot:
                AddIfMissing(slotNames, slot.Slot, $"_slot{slot.Slot}");
                AddIfMissing(slotTypes, slot.Slot, slot.TypeName);
                break;

            case FieldValue field:
                CollectSlots(field.Target, slotNames, slotTypes);
                break;

            case ArithValue arith:
                CollectSlots(arith.Left, slotNames, slotTypes);
                CollectSlots(arith.Right, slotNames, slotTypes);
                break;

            case ListConsValue cons:
                CollectSlots(cons.Head, slotNames, slotTypes);
                CollectSlots(cons.Tail, slotNames, slotTypes);
                break;
        }
    }

    private static void CollectLookupSlots(
        IndexedLookupSpec lookup,
        IDictionary<int, string> slotNames,
        IDictionary<int, string> slotTypes)
    {
        foreach (EqualityLookupPart part in lookup.EqualityParts)
            CollectSlots(part.Key, slotNames, slotTypes);

        if (lookup.Range?.Lower is not null)
            CollectSlots(lookup.Range.Lower, slotNames, slotTypes);

        if (lookup.Range?.Upper is not null)
            CollectSlots(lookup.Range.Upper, slotNames, slotTypes);
    }

    private static string InferTypeName(PlanValue value)
    {
        return value switch
        {
            SlotValue slot => slot.TypeName,
            ConstValue constant => constant.TypeName,
            FieldValue field => field.TypeName,
            ArithValue arith => InferTypeName(arith.Left),
            ListEmptyValue empty => $"global::Fletched.Core.LogicList<{empty.ElementTypeName}>",
            ListConsValue cons => $"global::Fletched.Core.LogicList<{cons.ElementTypeName}>",
            _ => "object"
        };
    }

    private static void AddIfMissing(IDictionary<int, string> values, int key, string value)
    {
        if (!TryGetValue(values, key, out _))
            values[key] = value;
    }

    private static string ResolveSlotName(IDictionary<int, string> values, int key)
    {
        return TryGetValue(values, key, out string value)
            ? value
            : $"_slot{key}";
    }

    private static bool TryGetValue(IDictionary<int, string> values, int key, out string value)
    {
        if (values.TryGetValue(key, out string? existing) && existing is not null)
        {
            value = existing;
            return true;
        }

        value = string.Empty;
        return false;
    }

    private static string GetCallResultTypeName(CallInstr call)
    {
        bool singleArityPredicate = call.PredicateType.GetMembers()
            .OfType<IMethodSymbol>()
            .Count(method => method.GetAttributes().Any(attr => attr.AttributeClass?.Name == "PredicateBodyAttribute")) == 1;

        string resultTypeName = singleArityPredicate
            ? $"{call.PredicateType.Name}Result"
            : $"{call.PredicateType.Name}Arity{call.Arity}Result";

        return SourceSymbolHelpers.GetQualifiedSiblingTypeName(call.PredicateType, resultTypeName);
    }

    private static string GetCallResultFieldName(CallInstr call, int argumentIndex)
    {
        IMethodSymbol bodyMethod = call.PredicateType.GetMembers()
            .OfType<IMethodSymbol>()
            .Single(method =>
                method.GetAttributes().Any(attr => attr.AttributeClass?.Name == "PredicateBodyAttribute")
                && method.Parameters.Length == call.Arity);

        return bodyMethod.Parameters[argumentIndex].Name;
    }

    private static string TablePropertyName(ITypeSymbol factType)
    {
        string name = factType.Name;
        return name.EndsWith("s") ? name : name + "s";
    }

    private static string Capitalize(string s) =>
        s.Length == 0 ? s : char.ToUpperInvariant(s[0]) + s.Substring(1);
}
